[package]
name = "mutantor"
version = "0.2.1"
edition = "2024"
license = "Apache-2.0"
description = "Core mutation testing engine"
repository = "https://github.com/Mahdi-Movahedian-Atar/mutantor"
readme = "readme.md"
keywords = ["mutation-testing", "testing"]
categories = ["development-tools::testing"]
[lib]

[features]
default = []
ai = ["default"]

[dependencies]
mutantor-macro = { path = "mutantor-macro",version = "0.2.1" }
mutantor-core = { path = "mutantor-core",version = "0.2.1" }

[workspace]
members = ["example_crate","mutantor-core","mutantor-macro"]
